#ifndef PODOSTATE_H
#define PODOSTATE_H

#include "RBSharedMemory.h"

#define NUM_JOINTS  18
enum{ WRIST_RIGHT = 0, WRIST_LEFT};

enum ROBOT_STATE_ARM{
    ROBOT_NOT_MOVE = 0,
    ROBOT_MOVING_WBIK,
    ROBOT_MOVING_JOINT,
    ROBOT_JOINT_PUBLISHED,
    ROBOT_JOINT_TRAJECTORY
};

enum ROBOT_STATE_BASE{
    BASE_NOT_MOVE = 0,
    BASE_MOVING,
    BASE_VEL_MOVING
};

typedef struct _SENSOR_DATA_
{
    FT_SENSOR FT[2];
    ENCODER_SENSOR ENCODER[NUM_JOINTS];
}SENSOR_DATA;

#endif // PODOSTATE_H
